### ISSUE TITLE
Default icon size

### ISSUE THREAD

**Issue by acodega** [aanklewicz/SFIcons#4]
We can debate this all day but I wonder if it makes sense to change the default symbol size to 75% of the icon size.

One thing to keep in mind is that SF Symbols are not monospaced. Some symbols like `clipboard` are rectangular, taller than they are wide. I'm sure some others are wider than they are tall. Perhaps having some preset options like 50%, 75%, 90%, and then an option to apply this to the height or the width would be a good place to start?

**Comment by aanklewicz** [comment]
https://github.com/user-attachments/assets/fc7050cc-2ce2-4382-9fde-1929e0c42caa

As discussed on Slack. I like the 50% as the default. But a slider is a good idea. I think. This is just a quick mockup.

**Comment by aanklewicz** [comment]
Version 1.2 has been released with this function. Can be downloaded from https://github.com/aanklewicz/SFIcons/releases
